repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: "v5.9.3"
      hooks:
          - id: isort
            types: [file, python]
    - repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
          - id: black
            types: [file, python]
            additional_dependencies: ["regex==2021.9.30"]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies:
                [
                    "flake8-comprehensions",
                    "flake8-debugger",
                    "flake8-eradicate",
                    "flake8-mutable",
                ]
    - repo: https://github.com/PyCQA/bandit
      rev: "1.7.1"
      hooks:
          - id: bandit
            args: ["--ini", ".bandit", "-r"]
